// NexisFinance Contract ABI
export const NEXIS_FINANCE_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "builder", type: "address" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "BuilderOnboarded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "FundsWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "builder", type: "address" },
      { indexed: true, name: "ideaId", type: "bytes32" },
      { indexed: false, name: "tier", type: "uint8" },
      { indexed: false, name: "expiry", type: "uint256" },
    ],
    name: "IdeaBoosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "builder", type: "address" },
      { indexed: true, name: "ideaId", type: "bytes32" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
    name: "IdeaListed",
    type: "event",
  },
  {
    inputs: [],
    name: "BASIC_BOOST_FEE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ELITE_BOOST_FEE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "EXTRA_IDEA_FEE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONBOARDING_FEE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRO_BOOST_FEE",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "builderIdeaCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "tier", type: "uint8" },
      { name: "ideaId", type: "bytes32" },
    ],
    name: "buyBoost",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBalance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "ideaId", type: "bytes32" }],
    name: "getBoostDetails",
    outputs: [
      { name: "active", type: "bool" },
      { name: "tier", type: "uint8" },
      { name: "expiry", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "builder", type: "address" }],
    name: "isVerifiedBuilder",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "ideaId", type: "bytes32" }],
    name: "isIdeaBoosted",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "ideaId", type: "bytes32" }],
    name: "listFreeIdea",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "ideaId", type: "bytes32" }],
    name: "payExtraIdea",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "payOnboarding",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "verifiedBuilders",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

// NexisDealNFT Contract ABI
export const NEXIS_DEAL_NFT_ABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "dealId", type: "bytes32" },
      { indexed: true, name: "builder", type: "address" },
      { indexed: true, name: "investor", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
    ],
    name: "DealConfirmed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "dealId", type: "bytes32" },
      { indexed: true, name: "investor", type: "address" },
    ],
    name: "DealRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "dealId", type: "bytes32" },
      { indexed: true, name: "builder", type: "address" },
      { indexed: true, name: "investor", type: "address" },
      { indexed: false, name: "startupName", type: "string" },
    ],
    name: "DealRequested",
    type: "event",
  },
  {
    inputs: [{ name: "dealId", type: "bytes32" }],
    name: "confirmDeal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "dealId", type: "bytes32" }],
    name: "getConfirmedDeal",
    outputs: [
      { name: "builder", type: "address" },
      { name: "investor", type: "address" },
      { name: "tokenId", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "dealId", type: "bytes32" }],
    name: "getPendingDeal",
    outputs: [
      { name: "builder", type: "address" },
      { name: "investor", type: "address" },
      { name: "tokenURI", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "dealId", type: "bytes32" }],
    name: "isDealPending",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "dealId", type: "bytes32" }],
    name: "rejectDeal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "investor", type: "address" },
      { name: "startupName", type: "string" },
      { name: "tokenURI", type: "string" },
    ],
    name: "requestDealConfirmation",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalDeals",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
